export const courses = [
  // === PEMASARAN ===
  {
    id: "1",
    title: "Big 4 Auditor Financial Analyst",
    instructor: "Jenna Ortega\nSenior Accountant",
    price: "Rp 300K",
    rating: "3.5 (68)",
    image: "/thumbnail/satu.jpeg",
    category: "Pemasaran",
    video: [
      {
        title: "Introduction to Course 1: Foundations of User Experience Design",
        type: "Video",
        duration: "12 Menit",
        expanded: true,
        items: [
          { title: "The basics of user experience design", type: "Video", duration: "12 Menit" },
          { title: "Jobs in the field of user experience", type: "Video", duration: "12 Menit" },
          { title: "The product development life cycle", type: "Video", duration: "12 Menit" },
        ],
      },
      {
        title: "Jobs in the field of user experience",
        type: "Video",
        duration: "12 Menit",
      },
      {
        title: "The product development life cycle",
        type: "Video",
        duration: "12 Menit",
      },
    ],
  },
  {
    id: "2",
    title: "Strategi Digital Marketing",
    instructor: "Reza Mahendra\nDigital Marketer",
    price: "Rp 250K",
    rating: "4.2 (120)",
    image: "/thumbnail/satu.jpeg",
    category: "Pemasaran",
    video: [
      {
        title: "Introduction to Course 1: Foundations of User Experience Design",
        type: "Video",
        duration: "12 Menit",
        expanded: true,
        items: [
          { title: "The basics of user experience design", type: "Video", duration: "12 Menit" },
          { title: "Jobs in the field of user experience", type: "Video", duration: "12 Menit" },
          { title: "The product development life cycle", type: "Video", duration: "12 Menit" },
        ],
      },
      {
        title: "Jobs in the field of user experience",
        type: "Video",
        duration: "12 Menit",
      },
      {
        title: "The product development life cycle",
        type: "Video",
        duration: "12 Menit",
      },
    ],
  },
  {
    id: "3",
    title: "SEO & SEM Optimization",
    instructor: "Alia Fauzia\nSEO Expert",
    price: "Rp 200K",
    rating: "4.0 (87)",
    image: "/thumbnail/satu.jpeg",
    category: "Pemasaran",
    video: [
      {
        title: "Introduction to Course 1: Foundations of User Experience Design",
        type: "Video",
        duration: "12 Menit",
        expanded: true,
        items: [
          { title: "The basics of user experience design", type: "Video", duration: "12 Menit" },
          { title: "Jobs in the field of user experience", type: "Video", duration: "12 Menit" },
          { title: "The product development life cycle", type: "Video", duration: "12 Menit" },
        ],
      },
      {
        title: "Jobs in the field of user experience",
        type: "Video",
        duration: "12 Menit",
      },
      {
        title: "The product development life cycle",
        type: "Video",
        duration: "12 Menit",
      },
    ],
  },
  {
    id: "4",
    title: "Branding dan Positioning",
    instructor: "Dewi Lestari\nBrand Strategist",
    price: "Rp 270K",
    rating: "4.3 (93)",
    image: "/thumbnail/satu.jpeg",
    category: "Pemasaran",
    video: [
      {
        title: "Introduction to Course 1: Foundations of User Experience Design",
        type: "Video",
        duration: "12 Menit",
        expanded: true,
        items: [
          { title: "The basics of user experience design", type: "Video", duration: "12 Menit" },
          { title: "Jobs in the field of user experience", type: "Video", duration: "12 Menit" },
          { title: "The product development life cycle", type: "Video", duration: "12 Menit" },
        ],
      },
      {
        title: "Jobs in the field of user experience",
        type: "Video",
        duration: "12 Menit",
      },
      {
        title: "The product development life cycle",
        type: "Video",
        duration: "12 Menit",
      },
    ],
  },
  {
    id: "5",
    title: "Marketing Analytics Dasar",
    instructor: "Taufik Hidayat\nMarketing Analyst",
    price: "Rp 280K",
    rating: "4.4 (101)",
    image: "/thumbnail/satu.jpeg",
    category: "Pemasaran",
    video: [
      {
        title: "Introduction to Course 1: Foundations of User Experience Design",
        type: "Video",
        duration: "12 Menit",
        expanded: true,
        items: [
          { title: "The basics of user experience design", type: "Video", duration: "12 Menit" },
          { title: "Jobs in the field of user experience", type: "Video", duration: "12 Menit" },
          { title: "The product development life cycle", type: "Video", duration: "12 Menit" },
        ],
      },
      {
        title: "Jobs in the field of user experience",
        type: "Video",
        duration: "12 Menit",
      },
      {
        title: "The product development life cycle",
        type: "Video",
        duration: "12 Menit",
      },
    ],
  },
  {
    id: "6",
    title: "Email Marketing Automation",
    instructor: "Karina Putri\nCampaign Specialist",
    price: "Rp 210K",
    rating: "4.1 (72)",
    image: "/thumbnail/satu.jpeg",
    category: "Pemasaran",
    video: [
      {
        title: "Introduction to Course 1: Foundations of User Experience Design",
        type: "Video",
        duration: "12 Menit",
        expanded: true,
        items: [
          { title: "The basics of user experience design", type: "Video", duration: "12 Menit" },
          { title: "Jobs in the field of user experience", type: "Video", duration: "12 Menit" },
          { title: "The product development life cycle", type: "Video", duration: "12 Menit" },
        ],
      },
      {
        title: "Jobs in the field of user experience",
        type: "Video",
        duration: "12 Menit",
      },
      {
        title: "The product development life cycle",
        type: "Video",
        duration: "12 Menit",
      },
    ],
  },
  {
    id: "7",
    title: "Content Marketing Mastery",
    instructor: "Ari Wibowo\nContent Strategist",
    price: "Rp 230K",
    rating: "4.0 (89)",
    image: "/thumbnail/satu.jpeg",
    category: "Pemasaran",
    video: [
      {
        title: "Introduction to Course 1: Foundations of User Experience Design",
        type: "Video",
        duration: "12 Menit",
        expanded: true,
        items: [
          { title: "The basics of user experience design", type: "Video", duration: "12 Menit" },
          { title: "Jobs in the field of user experience", type: "Video", duration: "12 Menit" },
          { title: "The product development life cycle", type: "Video", duration: "12 Menit" },
        ],
      },
      {
        title: "Jobs in the field of user experience",
        type: "Video",
        duration: "12 Menit",
      },
      {
        title: "The product development life cycle",
        type: "Video",
        duration: "12 Menit",
      },
    ],
  },
  {
    id: "8",
    title: "Facebook Ads for Business",
    instructor: "Lisa Andini\nAds Specialist",
    price: "Rp 260K",
    rating: "3.9 (77)",
    image: "/thumbnail/satu.jpeg",
    category: "Pemasaran",
    video: [
      {
        title: "Introduction to Course 1: Foundations of User Experience Design",
        type: "Video",
        duration: "12 Menit",
        expanded: true,
        items: [
          { title: "The basics of user experience design", type: "Video", duration: "12 Menit" },
          { title: "Jobs in the field of user experience", type: "Video", duration: "12 Menit" },
          { title: "The product development life cycle", type: "Video", duration: "12 Menit" },
        ],
      },
      {
        title: "Jobs in the field of user experience",
        type: "Video",
        duration: "12 Menit",
      },
      {
        title: "The product development life cycle",
        type: "Video",
        duration: "12 Menit",
      },
    ],
  },
  {
    id: "9",
    title: "TikTok Marketing Strategy",
    instructor: "Nina Saputra\nSocial Media Expert",
    price: "Rp 250K",
    rating: "4.2 (84)",
    image: "/thumbnail/satu.jpeg",
    category: "Pemasaran",
    video: [
      {
        title: "Introduction to Course 1: Foundations of User Experience Design",
        type: "Video",
        duration: "12 Menit",
        expanded: true,
        items: [
          { title: "The basics of user experience design", type: "Video", duration: "12 Menit" },
          { title: "Jobs in the field of user experience", type: "Video", duration: "12 Menit" },
          { title: "The product development life cycle", type: "Video", duration: "12 Menit" },
        ],
      },
      {
        title: "Jobs in the field of user experience",
        type: "Video",
        duration: "12 Menit",
      },
      {
        title: "The product development life cycle",
        type: "Video",
        duration: "12 Menit",
      },
    ],
  },

  // === DESAIN ===
  {
    id: "10",
    title: "Fundamental UI/UX Design",
    instructor: "Dian Kartika\nUI/UX Designer",
    price: "Rp 320K",
    rating: "4.5 (134)",
    image: "/thumbnail/satu.jpeg",
    category: "Desain",
    video: [
      {
        title: "Introduction to Course 1: Foundations of User Experience Design",
        type: "Video",
        duration: "12 Menit",
        expanded: true,
        items: [
          { title: "The basics of user experience design", type: "Video", duration: "12 Menit" },
          { title: "Jobs in the field of user experience", type: "Video", duration: "12 Menit" },
          { title: "The product development life cycle", type: "Video", duration: "12 Menit" },
        ],
      },
      {
        title: "Jobs in the field of user experience",
        type: "Video",
        duration: "12 Menit",
      },
      {
        title: "The product development life cycle",
        type: "Video",
        duration: "12 Menit",
      },
    ],
  },
  {
    id: "11",
    title: "Adobe Photoshop Masterclass",
    instructor: "Kevin Santoso\nGraphic Designer",
    price: "Rp 300K",
    rating: "4.3 (102)",
    image: "/thumbnail/satu.jpeg",
    category: "Desain",
    video: [
      {
        title: "Introduction to Course 1: Foundations of User Experience Design",
        type: "Video",
        duration: "12 Menit",
        expanded: true,
        items: [
          { title: "The basics of user experience design", type: "Video", duration: "12 Menit" },
          { title: "Jobs in the field of user experience", type: "Video", duration: "12 Menit" },
          { title: "The product development life cycle", type: "Video", duration: "12 Menit" },
        ],
      },
      {
        title: "Jobs in the field of user experience",
        type: "Video",
        duration: "12 Menit",
      },
      {
        title: "The product development life cycle",
        type: "Video",
        duration: "12 Menit",
      },
    ],
  },
  {
    id: "12",
    title: "Canva untuk Bisnis",
    instructor: "Putri Ayu\nCreative Designer",
    price: "Rp 150K",
    rating: "4.1 (88)",
    image: "/thumbnail/satu.jpeg",
    category: "Desain",
    video: [
      {
        title: "Introduction to Course 1: Foundations of User Experience Design",
        type: "Video",
        duration: "12 Menit",
        expanded: true,
        items: [
          { title: "The basics of user experience design", type: "Video", duration: "12 Menit" },
          { title: "Jobs in the field of user experience", type: "Video", duration: "12 Menit" },
          { title: "The product development life cycle", type: "Video", duration: "12 Menit" },
        ],
      },
      {
        title: "Jobs in the field of user experience",
        type: "Video",
        duration: "12 Menit",
      },
      {
        title: "The product development life cycle",
        type: "Video",
        duration: "12 Menit",
      },
    ],
  },
  {
    id: "13",
    title: "Illustrator dari Nol",
    instructor: "Yoga Pratama\nVector Artist",
    price: "Rp 275K",
    rating: "4.4 (93)",
    image: "/thumbnail/satu.jpeg",
    category: "Desain",
    video: [
      {
        title: "Introduction to Course 1: Foundations of User Experience Design",
        type: "Video",
        duration: "12 Menit",
        expanded: true,
        items: [
          { title: "The basics of user experience design", type: "Video", duration: "12 Menit" },
          { title: "Jobs in the field of user experience", type: "Video", duration: "12 Menit" },
          { title: "The product development life cycle", type: "Video", duration: "12 Menit" },
        ],
      },
      {
        title: "Jobs in the field of user experience",
        type: "Video",
        duration: "12 Menit",
      },
      {
        title: "The product development life cycle",
        type: "Video",
        duration: "12 Menit",
      },
    ],
  },
  {
    id: "14",
    title: "Membuat Portofolio Digital",
    instructor: "Indah Lestari\nVisual Designer",
    price: "Rp 220K",
    rating: "4.2 (77)",
    image: "/thumbnail/satu.jpeg",
    category: "Desain",
    video: [
      {
        title: "Introduction to Course 1: Foundations of User Experience Design",
        type: "Video",
        duration: "12 Menit",
        expanded: true,
        items: [
          { title: "The basics of user experience design", type: "Video", duration: "12 Menit" },
          { title: "Jobs in the field of user experience", type: "Video", duration: "12 Menit" },
          { title: "The product development life cycle", type: "Video", duration: "12 Menit" },
        ],
      },
      {
        title: "Jobs in the field of user experience",
        type: "Video",
        duration: "12 Menit",
      },
      {
        title: "The product development life cycle",
        type: "Video",
        duration: "12 Menit",
      },
    ],
  },
  {
    id: "15",
    title: "Design Thinking untuk Pemula",
    instructor: "Rian Hidayat\nProduct Designer",
    price: "Rp 260K",
    rating: "4.0 (81)",
    image: "/thumbnail/satu.jpeg",
    category: "Desain",
    video: [
      {
        title: "Introduction to Course 1: Foundations of User Experience Design",
        type: "Video",
        duration: "12 Menit",
        expanded: true,
        items: [
          { title: "The basics of user experience design", type: "Video", duration: "12 Menit" },
          { title: "Jobs in the field of user experience", type: "Video", duration: "12 Menit" },
          { title: "The product development life cycle", type: "Video", duration: "12 Menit" },
        ],
      },
      {
        title: "Jobs in the field of user experience",
        type: "Video",
        duration: "12 Menit",
      },
      {
        title: "The product development life cycle",
        type: "Video",
        duration: "12 Menit",
      },
    ],
  },
  {
    id: "16",
    title: "Figma Advanced",
    instructor: "Aditya Saputra\nUI Specialist",
    price: "Rp 310K",
    rating: "4.5 (97)",
    image: "/thumbnail/satu.jpeg",
    category: "Desain",
    video: [
      {
        title: "Introduction to Course 1: Foundations of User Experience Design",
        type: "Video",
        duration: "12 Menit",
        expanded: true,
        items: [
          { title: "The basics of user experience design", type: "Video", duration: "12 Menit" },
          { title: "Jobs in the field of user experience", type: "Video", duration: "12 Menit" },
          { title: "The product development life cycle", type: "Video", duration: "12 Menit" },
        ],
      },
      {
        title: "Jobs in the field of user experience",
        type: "Video",
        duration: "12 Menit",
      },
      {
        title: "The product development life cycle",
        type: "Video",
        duration: "12 Menit",
      },
    ],
  },
  {
    id: "17",
    title: "Mobile App UI Design",
    instructor: "Aulia Rachma\nUI/UX Freelancer",
    price: "Rp 290K",
    rating: "4.3 (88)",
    image: "/thumbnail/satu.jpeg",
    category: "Desain",
    video: [
      {
        title: "Introduction to Course 1: Foundations of User Experience Design",
        type: "Video",
        duration: "12 Menit",
        expanded: true,
        items: [
          { title: "The basics of user experience design", type: "Video", duration: "12 Menit" },
          { title: "Jobs in the field of user experience", type: "Video", duration: "12 Menit" },
          { title: "The product development life cycle", type: "Video", duration: "12 Menit" },
        ],
      },
      {
        title: "Jobs in the field of user experience",
        type: "Video",
        duration: "12 Menit",
      },
      {
        title: "The product development life cycle",
        type: "Video",
        duration: "12 Menit",
      },
    ],
  },
  {
    id: "18",
    title: "Layouting & Typography",
    instructor: "Niko Prasetyo\nPrint Designer",
    price: "Rp 240K",
    rating: "4.1 (79)",
    image: "/thumbnail/satu.jpeg",
    category: "Desain",
    video: [
      {
        title: "Introduction to Course 1: Foundations of User Experience Design",
        type: "Video",
        duration: "12 Menit",
        expanded: true,
        items: [
          { title: "The basics of user experience design", type: "Video", duration: "12 Menit" },
          { title: "Jobs in the field of user experience", type: "Video", duration: "12 Menit" },
          { title: "The product development life cycle", type: "Video", duration: "12 Menit" },
        ],
      },
      {
        title: "Jobs in the field of user experience",
        type: "Video",
        duration: "12 Menit",
      },
      {
        title: "The product development life cycle",
        type: "Video",
        duration: "12 Menit",
      },
    ],
  },

  // === Pengembangan Diri ===
  {
    id: "19",
    title: "Web Dev dengan HTML, CSS, JS",
    instructor: "Agus Riyadi\nWeb Developer",
    price: "Rp 280K",
    rating: "4.4 (103)",
    image: "/thumbnail/satu.jpeg",
    category: "Pengembangan Diri",
    video: [
      {
        title: "Introduction to Course 1: Foundations of User Experience Design",
        type: "Video",
        duration: "12 Menit",
        expanded: true,
        items: [
          { title: "The basics of user experience design", type: "Video", duration: "12 Menit" },
          { title: "Jobs in the field of user experience", type: "Video", duration: "12 Menit" },
          { title: "The product development life cycle", type: "Video", duration: "12 Menit" },
        ],
      },
      {
        title: "Jobs in the field of user experience",
        type: "Video",
        duration: "12 Menit",
      },
      {
        title: "The product development life cycle",
        type: "Video",
        duration: "12 Menit",
      },
    ],
  },
  {
    id: "20",
    title: "React untuk Pemula",
    instructor: "Siti Rahma\nFrontend Engineer",
    price: "Rp 300K",
    rating: "4.3 (100)",
    image: "/thumbnail/satu.jpeg",
    category: "Pengembangan Diri",
    video: [
      {
        title: "Introduction to Course 1: Foundations of User Experience Design",
        type: "Video",
        duration: "12 Menit",
        expanded: true,
        items: [
          { title: "The basics of user experience design", type: "Video", duration: "12 Menit" },
          { title: "Jobs in the field of user experience", type: "Video", duration: "12 Menit" },
          { title: "The product development life cycle", type: "Video", duration: "12 Menit" },
        ],
      },
      {
        title: "Jobs in the field of user experience",
        type: "Video",
        duration: "12 Menit",
      },
      {
        title: "The product development life cycle",
        type: "Video",
        duration: "12 Menit",
      },
    ],
  },
  {
    id: "21",
    title: "Kotlin Android Developer",
    instructor: "Dimas Prakoso\nMobile Dev",
    price: "Rp 320K",
    rating: "4.5 (120)",
    image: "/thumbnail/satu.jpeg",
    category: "Pengembangan Diri",
    video: [
      {
        title: "Introduction to Course 1: Foundations of User Experience Design",
        type: "Video",
        duration: "12 Menit",
        expanded: true,
        items: [
          { title: "The basics of user experience design", type: "Video", duration: "12 Menit" },
          { title: "Jobs in the field of user experience", type: "Video", duration: "12 Menit" },
          { title: "The product development life cycle", type: "Video", duration: "12 Menit" },
        ],
      },
      {
        title: "Jobs in the field of user experience",
        type: "Video",
        duration: "12 Menit",
      },
      {
        title: "The product development life cycle",
        type: "Video",
        duration: "12 Menit",
      },
    ],
  },
  {
    id: "22",
    title: "Laravel Framework Dasar",
    instructor: "Budi Santosa\nBackend Developer",
    price: "Rp 290K",
    rating: "4.2 (89)",
    image: "/thumbnail/satu.jpeg",
    category: "Pengembangan Diri",
    video: [
      {
        title: "Introduction to Course 1: Foundations of User Experience Design",
        type: "Video",
        duration: "12 Menit",
        expanded: true,
        items: [
          { title: "The basics of user experience design", type: "Video", duration: "12 Menit" },
          { title: "Jobs in the field of user experience", type: "Video", duration: "12 Menit" },
          { title: "The product development life cycle", type: "Video", duration: "12 Menit" },
        ],
      },
      {
        title: "Jobs in the field of user experience",
        type: "Video",
        duration: "12 Menit",
      },
      {
        title: "The product development life cycle",
        type: "Video",
        duration: "12 Menit",
      },
    ],
  },
  {
    id: "23",
    title: "Python untuk Data Science",
    instructor: "Laras Widya\nData Analyst",
    price: "Rp 310K",
    rating: "4.6 (130)",
    image: "/thumbnail/satu.jpeg",
    category: "Pengembangan Diri",
    video: [
      {
        title: "Introduction to Course 1: Foundations of User Experience Design",
        type: "Video",
        duration: "12 Menit",
        expanded: true,
        items: [
          { title: "The basics of user experience design", type: "Video", duration: "12 Menit" },
          { title: "Jobs in the field of user experience", type: "Video", duration: "12 Menit" },
          { title: "The product development life cycle", type: "Video", duration: "12 Menit" },
        ],
      },
      {
        title: "Jobs in the field of user experience",
        type: "Video",
        duration: "12 Menit",
      },
      {
        title: "The product development life cycle",
        type: "Video",
        duration: "12 Menit",
      },
    ],
  },
  {
    id: "24",
    title: "Git & GitHub Workshop",
    instructor: "Eko Susilo\nDevOps",
    price: "Rp 200K",
    rating: "4.0 (75)",
    image: "/thumbnail/satu.jpeg",
    category: "Pengembangan Diri",
    video: [
      {
        title: "Introduction to Course 1: Foundations of User Experience Design",
        type: "Video",
        duration: "12 Menit",
        expanded: true,
        items: [
          { title: "The basics of user experience design", type: "Video", duration: "12 Menit" },
          { title: "Jobs in the field of user experience", type: "Video", duration: "12 Menit" },
          { title: "The product development life cycle", type: "Video", duration: "12 Menit" },
        ],
      },
      {
        title: "Jobs in the field of user experience",
        type: "Video",
        duration: "12 Menit",
      },
      {
        title: "The product development life cycle",
        type: "Video",
        duration: "12 Menit",
      },
    ],
  },
  {
    id: "25",
    title: "JavaScript Lanjutan",
    instructor: "Farah Lestari\nSoftware Engineer",
    price: "Rp 270K",
    rating: "4.1 (91)",
    image: "/thumbnail/satu.jpeg",
    category: "Pengembangan Diri",
    video: [
      {
        title: "Introduction to Course 1: Foundations of User Experience Design",
        type: "Video",
        duration: "12 Menit",
        expanded: true,
        items: [
          { title: "The basics of user experience design", type: "Video", duration: "12 Menit" },
          { title: "Jobs in the field of user experience", type: "Video", duration: "12 Menit" },
          { title: "The product development life cycle", type: "Video", duration: "12 Menit" },
        ],
      },
      {
        title: "Jobs in the field of user experience",
        type: "Video",
        duration: "12 Menit",
      },
      {
        title: "The product development life cycle",
        type: "Video",
        duration: "12 Menit",
      },
    ],
  },
  {
    id: "26",
    title: "Machine Learning Dasar",
    instructor: "Rizky Hadi\nML Engineer",
    price: "Rp 350K",
    rating: "4.7 (140)",
    image: "/thumbnail/satu.jpeg",
    category: "Pengembangan Diri",
    video: [
      {
        title: "Introduction to Course 1: Foundations of User Experience Design",
        type: "Video",
        duration: "12 Menit",
        expanded: true,
        items: [
          { title: "The basics of user experience design", type: "Video", duration: "12 Menit" },
          { title: "Jobs in the field of user experience", type: "Video", duration: "12 Menit" },
          { title: "The product development life cycle", type: "Video", duration: "12 Menit" },
        ],
      },
      {
        title: "Jobs in the field of user experience",
        type: "Video",
        duration: "12 Menit",
      },
      {
        title: "The product development life cycle",
        type: "Video",
        duration: "12 Menit",
      },
    ],
  },
  {
    id: "27",
    title: "REST API dengan Node.js",
    instructor: "Anita Zahra\nBackend Specialist",
    price: "Rp 285K",
    rating: "4.3 (99)",
    image: "/thumbnail/satu.jpeg",
    category: "Pengembangan Diri",
    video: [
      {
        title: "Introduction to Course 1: Foundations of User Experience Design",
        type: "Video",
        duration: "12 Menit",
        expanded: true,
        items: [
          { title: "The basics of user experience design", type: "Video", duration: "12 Menit" },
          { title: "Jobs in the field of user experience", type: "Video", duration: "12 Menit" },
          { title: "The product development life cycle", type: "Video", duration: "12 Menit" },
        ],
      },
      {
        title: "Jobs in the field of user experience",
        type: "Video",
        duration: "12 Menit",
      },
      {
        title: "The product development life cycle",
        type: "Video",
        duration: "12 Menit",
      },
    ],
  },
  // === Pengembangan Diri ===
  {
    id: "28",
    title: "Web Dev dengan HTML, CSS, JS",
    instructor: "Agus Riyadi\nWeb Developer",
    price: "Rp 280K",
    rating: "4.4 (103)",
    image: "/thumbnail/satu.jpeg",
    category: "Pengembangan Diri",
    video: [
      {
        title: "Introduction to Course 1: Foundations of User Experience Design",
        type: "Video",
        duration: "12 Menit",
        expanded: true,
        items: [
          { title: "The basics of user experience design", type: "Video", duration: "12 Menit" },
          { title: "Jobs in the field of user experience", type: "Video", duration: "12 Menit" },
          { title: "The product development life cycle", type: "Video", duration: "12 Menit" },
        ],
      },
      {
        title: "Jobs in the field of user experience",
        type: "Video",
        duration: "12 Menit",
      },
      {
        title: "The product development life cycle",
        type: "Video",
        duration: "12 Menit",
      },
    ],
  },
  {
    id: "29",
    title: "React untuk Pemula",
    instructor: "Siti Rahma\nFrontend Engineer",
    price: "Rp 300K",
    rating: "4.3 (100)",
    image: "/thumbnail/satu.jpeg",
    category: "Pengembangan Diri",
    video: [
      {
        title: "Introduction to Course 1: Foundations of User Experience Design",
        type: "Video",
        duration: "12 Menit",
        expanded: true,
        items: [
          { title: "The basics of user experience design", type: "Video", duration: "12 Menit" },
          { title: "Jobs in the field of user experience", type: "Video", duration: "12 Menit" },
          { title: "The product development life cycle", type: "Video", duration: "12 Menit" },
        ],
      },
      {
        title: "Jobs in the field of user experience",
        type: "Video",
        duration: "12 Menit",
      },
      {
        title: "The product development life cycle",
        type: "Video",
        duration: "12 Menit",
      },
    ],
  },
  {
    id: "30",
    title: "Kotlin Android Developer",
    instructor: "Dimas Prakoso\nMobile Dev",
    price: "Rp 320K",
    rating: "4.5 (120)",
    image: "/thumbnail/satu.jpeg",
    category: "Pengembangan Diri",
    video: [
      {
        title: "Introduction to Course 1: Foundations of User Experience Design",
        type: "Video",
        duration: "12 Menit",
        expanded: true,
        items: [
          { title: "The basics of user experience design", type: "Video", duration: "12 Menit" },
          { title: "Jobs in the field of user experience", type: "Video", duration: "12 Menit" },
          { title: "The product development life cycle", type: "Video", duration: "12 Menit" },
        ],
      },
      {
        title: "Jobs in the field of user experience",
        type: "Video",
        duration: "12 Menit",
      },
      {
        title: "The product development life cycle",
        type: "Video",
        duration: "12 Menit",
      },
    ],
  },
  {
    id: "31",
    title: "Laravel Framework Dasar",
    instructor: "Budi Santosa\nBackend Developer",
    price: "Rp 290K",
    rating: "4.2 (89)",
    image: "/thumbnail/satu.jpeg",
    category: "Pengembangan Diri",
    video: [
      {
        title: "Introduction to Course 1: Foundations of User Experience Design",
        type: "Video",
        duration: "12 Menit",
        expanded: true,
        items: [
          { title: "The basics of user experience design", type: "Video", duration: "12 Menit" },
          { title: "Jobs in the field of user experience", type: "Video", duration: "12 Menit" },
          { title: "The product development life cycle", type: "Video", duration: "12 Menit" },
        ],
      },
      {
        title: "Jobs in the field of user experience",
        type: "Video",
        duration: "12 Menit",
      },
      {
        title: "The product development life cycle",
        type: "Video",
        duration: "12 Menit",
      },
    ],
  },
  {
    id: "32",
    title: "Python untuk Data Science",
    instructor: "Laras Widya\nData Analyst",
    price: "Rp 310K",
    rating: "4.6 (130)",
    image: "/thumbnail/satu.jpeg",
    category: "Pengembangan Diri",
    video: [
      {
        title: "Introduction to Course 1: Foundations of User Experience Design",
        type: "Video",
        duration: "12 Menit",
        expanded: true,
        items: [
          { title: "The basics of user experience design", type: "Video", duration: "12 Menit" },
          { title: "Jobs in the field of user experience", type: "Video", duration: "12 Menit" },
          { title: "The product development life cycle", type: "Video", duration: "12 Menit" },
        ],
      },
      {
        title: "Jobs in the field of user experience",
        type: "Video",
        duration: "12 Menit",
      },
      {
        title: "The product development life cycle",
        type: "Video",
        duration: "12 Menit",
      },
    ],
  },
  {
    id: "33",
    title: "Git & GitHub Workshop",
    instructor: "Eko Susilo\nDevOps",
    price: "Rp 200K",
    rating: "4.0 (75)",
    image: "/thumbnail/satu.jpeg",
    category: "Pengembangan Diri",
    video: [
      {
        title: "Introduction to Course 1: Foundations of User Experience Design",
        type: "Video",
        duration: "12 Menit",
        expanded: true,
        items: [
          { title: "The basics of user experience design", type: "Video", duration: "12 Menit" },
          { title: "Jobs in the field of user experience", type: "Video", duration: "12 Menit" },
          { title: "The product development life cycle", type: "Video", duration: "12 Menit" },
        ],
      },
      {
        title: "Jobs in the field of user experience",
        type: "Video",
        duration: "12 Menit",
      },
      {
        title: "The product development life cycle",
        type: "Video",
        duration: "12 Menit",
      },
    ],
  },
  {
    id: "34",
    title: "JavaScript Lanjutan",
    instructor: "Farah Lestari\nSoftware Engineer",
    price: "Rp 270K",
    rating: "4.1 (91)",
    image: "/thumbnail/satu.jpeg",
    category: "Pengembangan Diri",
    video: [
      {
        title: "Introduction to Course 1: Foundations of User Experience Design",
        type: "Video",
        duration: "12 Menit",
        expanded: true,
        items: [
          { title: "The basics of user experience design", type: "Video", duration: "12 Menit" },
          { title: "Jobs in the field of user experience", type: "Video", duration: "12 Menit" },
          { title: "The product development life cycle", type: "Video", duration: "12 Menit" },
        ],
      },
      {
        title: "Jobs in the field of user experience",
        type: "Video",
        duration: "12 Menit",
      },
      {
        title: "The product development life cycle",
        type: "Video",
        duration: "12 Menit",
      },
    ],
  },
  {
    id: "35",
    title: "Machine Learning Dasar",
    instructor: "Rizky Hadi\nML Engineer",
    price: "Rp 350K",
    rating: "4.7 (140)",
    image: "/thumbnail/satu.jpeg",
    category: "Pengembangan Diri",
    video: [
      {
        title: "Introduction to Course 1: Foundations of User Experience Design",
        type: "Video",
        duration: "12 Menit",
        expanded: true,
        items: [
          { title: "The basics of user experience design", type: "Video", duration: "12 Menit" },
          { title: "Jobs in the field of user experience", type: "Video", duration: "12 Menit" },
          { title: "The product development life cycle", type: "Video", duration: "12 Menit" },
        ],
      },
      {
        title: "Jobs in the field of user experience",
        type: "Video",
        duration: "12 Menit",
      },
      {
        title: "The product development life cycle",
        type: "Video",
        duration: "12 Menit",
      },
    ],
  },
  {
    id: "36",
    title: "REST API dengan Node.js",
    instructor: "Anita Zahra\nBackend Specialist",
    price: "Rp 285K",
    rating: "4.3 (99)",
    image: "/thumbnail/sembilan.jpeg",
    video: [
      {
        title: "Introduction to Course 1: Foundations of User Experience Design",
        type: "Video",
        duration: "12 Menit",
        expanded: true,
        items: [
          { title: "The basics of user experience design", type: "Video", duration: "12 Menit" },
          { title: "Jobs in the field of user experience", type: "Video", duration: "12 Menit" },
          { title: "The product development life cycle", type: "Video", duration: "12 Menit" },
        ],
      },
      {
        title: "Jobs in the field of user experience",
        type: "Video",
        duration: "12 Menit",
      },
      {
        title: "The product development life cycle",
        type: "Video",
        duration: "12 Menit",
      },
    ],
    category: "Bisni",
  },
];
